plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@ojkelly/plugin-bundle.cjs
    spec: "https://yarn.build/latest/bundle"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
